# Generated by Django 5.0.3 on 2024-04-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_contact',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
