# Generated by Django 5.0.3 on 2024-04-03 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_stu_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='aadhar',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.aadhar'),
            preserve_default=False,
        ),
    ]
